# Generated by Django 3.2.5 on 2021-07-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='title',
            field=models.TextField(verbose_name='title'),
        ),
    ]
