# Generated by Django 3.2.5 on 2021-07-27 13:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210727_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='title'),
        ),
    ]
