# Generated by Django 3.2.5 on 2021-07-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_genre_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='main.rubrics'),
        ),
    ]
