# Generated by Django 3.2.2 on 2021-07-10 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Rasmi')),
                ('birthday', models.CharField(blank=True, max_length=50, verbose_name='T. sanasi')),
                ('phone', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Manzili')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
