# Generated by Django 3.2.2 on 2021-07-10 21:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=datetime.datetime(2021, 7, 10, 21, 22, 37, 589309, tzinfo=utc), upload_to='user_images/', verbose_name='Rasmi'),
            preserve_default=False,
        ),
    ]
