# Generated by Django 3.2.2 on 2021-07-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_img/default.jpg', null=True, upload_to='user_images/', verbose_name='Rasmi'),
        ),
    ]
