# Generated by Django 3.2.5 on 2021-07-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='*')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='*')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Author')),
                ('author_image', models.ImageField(blank=True, upload_to='Author_Images/', verbose_name='Author Image')),
                ('Tags', models.ManyToManyField(to='main.Tags')),
            ],
        ),
    ]
