# Generated by Django 3.2.5 on 2021-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quote_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='body',
            field=models.TextField(blank=True, verbose_name='body'),
        ),
    ]
