# Generated by Django 3.0.5 on 2021-08-07 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismingiz')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.Point')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
