# Generated by Django 3.0.5 on 2021-08-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210807_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(related_name='user_liked_posts', to='main.Point'),
        ),
        migrations.RemoveField(
            model_name='point',
            name='dislike',
        ),
        migrations.AddField(
            model_name='point',
            name='dislike',
            field=models.PositiveIntegerField(default=0, verbose_name='DisLike Count'),
        ),
        migrations.RemoveField(
            model_name='point',
            name='like',
        ),
        migrations.AddField(
            model_name='point',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Like Count'),
        ),
    ]
