# Generated by Django 3.2.2 on 2021-08-10 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='*')),
                ('image', models.ImageField(upload_to='gadgets_images/', verbose_name='Image')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='published')),
                ('file_format', models.CharField(blank=True, max_length=300, verbose_name='Format')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.category')),
                ('tag', models.ManyToManyField(related_name='tags', to='main.Tag')),
            ],
            options={
                'verbose_name_plural': 'Gadgets',
                'ordering': ['published'],
            },
        ),
    ]
