# Generated by Django 3.2.5 on 2021-07-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('old_price', models.PositiveIntegerField(blank=True, verbose_name='old price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/', verbose_name='food image')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='main.category')),
            ],
        ),
    ]
