# Generated by Django 3.2.5 on 2021-07-23 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 7, 23, 11, 38, 30, 973964, tzinfo=utc), unique=True, verbose_name='*'),
            preserve_default=False,
        ),
    ]
