# Generated by Django 3.2.5 on 2021-07-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='old price'),
        ),
    ]
