# Generated by Django 3.2.4 on 2021-07-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='*')),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.AlterModelOptions(
            name='rubrics',
            options={'verbose_name_plural': 'Rubrics'},
        ),
        migrations.AlterField(
            model_name='rubrics',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='*'),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='*')),
                ('poster', models.ImageField(upload_to='movie_posters/', verbose_name='Movie poster')),
                ('description', models.TextField(blank=True, verbose_name='Movie description')),
                ('director', models.CharField(max_length=100, verbose_name='Film director')),
                ('actors', models.CharField(max_length=200, verbose_name='Film actors')),
                ('year', models.PositiveIntegerField(default=0)),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('duration', models.CharField(max_length=100, verbose_name='Duration')),
                ('genre', models.ManyToManyField(related_name='genres', to='movie.Genre')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='movie.rubrics')),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
