# Generated by Django 3.2.4 on 2021-07-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210729_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dislike',
            field=models.PositiveIntegerField(default=0, verbose_name='DisLikes'),
        ),
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
    ]
