# Generated by Django 3.2.5 on 2021-08-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='color',
            field=models.CharField(choices=[('bg-warning', 'warning'), ('bg-danger', 'danger'), ('bg-primary', 'primary'), ('bg-info', 'info'), ('bg-success', 'success')], max_length=50, verbose_name='Rangi'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='star',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Yulduzi'),
        ),
    ]
