# Generated by Django 3.2.1 on 2021-08-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Ismi')),
                ('phone', models.PositiveIntegerField(blank=True, default=998, verbose_name='Telefon Raqami')),
                ('age', models.PositiveIntegerField(blank=True, default=0, verbose_name='Yoshi')),
                ('status', models.CharField(blank=True, choices=[('Keldi', 'Keldi'), ('Kelmad', 'Kelmadi'), ('Aniqmas', 'Aniqmas')], max_length=50, verbose_name='Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('cource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.cource')),
            ],
        ),
    ]
