# Generated by Django 3.2.5 on 2021-07-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='old price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Book_images/', verbose_name='Book image')),
                ('file', models.FileField(upload_to='book_files', verbose_name='Book itself')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main.category')),
            ],
        ),
    ]
