# Generated by Django 3.2.5 on 2021-07-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210726_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='instock',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Num'),
        ),
    ]
