# Generated by Django 3.2.5 on 2021-08-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=300, verbose_name='Email')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Rubrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='*')),
                ('poster', models.ImageField(blank=True, upload_to='movie/', verbose_name='Image')),
                ('movie', models.FileField(blank=True, upload_to='movies', verbose_name='File')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Director')),
                ('actors', models.CharField(blank=True, max_length=300, verbose_name='Actors ')),
                ('year', models.PositiveIntegerField(default=0, verbose_name='Year')),
                ('country', models.CharField(blank=True, max_length=500, verbose_name='Country')),
                ('genre', models.CharField(blank=True, max_length=200, verbose_name='Genre')),
                ('duration', models.CharField(max_length=100, verbose_name='Duration')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Published')),
                ('genres', models.ManyToManyField(related_name='movies', to='main.Genre')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='main.rubrics')),
            ],
        ),
    ]
